# Generated by Django 3.1.4 on 2020-12-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
